####################################################################
# Version 2.0
# Developed For 7.2.4 by: 
# Darley, Andrew E CTR NAVAIR, 724000D <andrew.darley.ctr@navy.mil>  
# Loscar, Joshua D CTR NAVAIR, 541400D  <joshua.loscar.ctr@navy.mil>
#      Changes 17Jun2019 JHMF
# Originally created for:
# Red Hat Enterprise Linux 7 Security Technical Implementation Guide 
# Release: 4 Benchmark Date: 26 Jan 2018
# 
# Version 5. 19Jun2019. General cleanup. Remove unneeded/wanted comment lines. JHMF
####################################################################

- name: Write file 
  template:
    src: "{{ role_path }}/templates/blank_rhel7_v2r4.ckl.template.ckl"
    dest: '{{out_file}}'

- name: Write cvs
  template:
    src: "{{ role_path }}/templates/blank_rhel7_v2r4.ckl.status.cvs"
    dest: '{{cvs_file}}'

#- name: Send mail
#  ignore_errors: True
#  mail:
#    host: localhost
#    port: '25'
#    to: john.h.faber.ctr@navy.mil
#    subject: Ansible-report System - {{out_file}}
#    body: 'System {{ ansible_hostname }} results are attached. {{out_file}}'
#    attach: '{{out_file}}'

