####################################################################
# Developed For 7.2.4 by:
# Darley, Andrew E CTR NAVAIR, 724000D <andrew.darley.ctr@navy.mil>  
# Loscar, Joshua D CTR NAVAIR, 541400D  <joshua.loscar.ctr@navy.mil>
#      
# Originally created for:
# Red Hat Enterprise Linux 7 Security Technical Implementation Guide 
# Release: 4 Benchmark Date: 26 Jan 2018
#
# Version 5. 19Jun2019. General cleanup. Remove unneeded/wanted comment lines. JHMF
#	Added "yum makecache fast" to improve "yum list" checks.
# 
####################################################################

- name: Prep
  file: path={{out_file}} owner={{ ansible_user }} group=users mode=640 state=touch

- name: Prep csv file
  file: path={{csv_file}} owner={{ ansible_user }} group=users mode=640 state=touch

- name: yum makecache fast
  shell: yum makecache fast >/dev/null 2>&1;echo
  args:
    executable: /bin/bash
  ignore_errors: True
  changed_when: False
