#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-09: re-wrote checks JHMF
#
#----------

- name: STIG RHEL7 V-72067 Check
  shell: yum -q list installed dracut-fips 2>&1
  args:
    executable: /bin/bash
  register: check1_72067
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72067 Check 2
  shell: yum -q list installed dracut-fips 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72067
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72067 Check 3
  shell: grep linux16 /boot/grub2/grub.cfg|head -1 |grep "fips=1"
  args:
    executable: /bin/bash
  register: check3_72067
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72067 Check 4
  shell: grep -x 1 /proc/sys/crypto/fips_enabled
  args:
    executable: /bin/bash
  register: check4_72067
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72067 Report
  set_fact: 
    status_72067: "{{ 'fail' if ((check2_72067.stdout == '') or (check3_72067.stdout == '') or (check4_72067.stdout == ''))else 'pass'}}"

#
