#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-07-26: Reviewed. JHMF
#
#----------

- name: STIG RHEL7 V-71925 Check
  shell: grep -i pass_min_days /etc/login.defs 2>&1
  args:
    executable: /bin/bash
  register: check1_71925
  ignore_errors: True
  changed_when: False
  tags:
      - V-71925
      - logindefs

- name: STIG RHEL7 V-71925 Check 2
  shell: grep -i pass_min_days /etc/login.defs | awk '!/^#/ && $2 >= 1'
  args:
    executable: /bin/bash
  register: check2_71925
  ignore_errors: True
  changed_when: False
  tags:
      - V-71925
      - logindefs

- name: STIG RHEL7 V-71925 Report
  set_fact: 
    status_71925: "{{ 'fail' if (check2_71925.stdout == '' ) else 'pass'}}"
  tags:
      - V-71925
      - logindefs

