#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71981 Check
  shell: grep repo_gpgcheck /etc/yum.conf
  args:
    executable: /bin/bash
  register: check1_71981
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71981 Check 2
  shell: grep repo_gpgcheck /etc/yum.conf 2>/dev/null | awk '/repo_gpgcheck=1/'
  args:
    executable: /bin/bash
  register: check2_71981
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71981 Report
  set_fact: 
    status_71981: "{{ 'fail' if (check2_71981.stdout != '') else 'pass'}}"

