#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-09: Check similiar to V-72041.  Pulled code from there JHMF
#
#----------

- name: STIG RHEL7 V-72059 Check
  shell: awk "-F:" '$3 > 100 && $7 !~ /false/ && $7 !~ /nologin/ && $6 !~ /\/$/ && $1 !~ /ldap/ {print $6}' /etc/passwd 2>&1
  args:
    executable: /bin/bash
  register: check1_72059
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72059 Check 2
  shell: for i in `awk "-F:" '$3 > 100 && $7 !~ /false/ && $7 !~ /nologin/ && $6 !~ /\/$/ && $1 !~ /ldap/ {print $6}' /etc/passwd`;do df -h $i;done|grep -v Filesystem|awk '{print $6}'|sort|uniq|xargs -iFS grep FS /etc/fstab
  args:
    executable: /bin/bash
  register: check2_72059
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72059 Report
  set_fact: 
    status_72059: "{{ 'fail' if (check2_72059.stdout == '') else 'pass'}}"

