#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-06: corrected checked file and changed grep to egrep to look for valid syslog servers 
#----------

- name: STIG RHEL7 V-72083 Check
  shell: grep -i remote_server /etc/audisp/audisp-remote.conf 2>&1
  args:
    executable: /bin/bash
  register: check1_72083
  ignore_errors: True
  changed_when: False
  tags:
      - V-72083
      - auditrules

- name: STIG RHEL7 V-72083 Check 2
  shell: egrep 'remote_server|172.30.20.61|172.16.5.35|cloudIP' /etc/audisp/audisp-remote.conf | awk '/^remote_server = /' 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72083
  ignore_errors: True
  changed_when: False
  tags:
      - V-72083
      - auditrules

- name: STIG RHEL7 V-72083 Report
  set_fact: 
    status_72083: "{{ 'fail' if (check2_72083.stdout == '') else 'pass'}}"
  tags:
      - V-72083
      - auditrules

