#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71919 Check
  shell:  grep password /etc/pam.d/system-auth-ac 
  args:
    executable: /bin/bash
  register: check1_71919
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71919 Check 2
  shell:  grep password /etc/pam.d/system-auth-ac | awk '/512/'
  args:
    executable: /bin/bash
  register: check2_71919
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71919 Report
  set_fact: 
    status_71919: "{{ 'fail' if (check2_71919.stdout == '' ) else 'pass'}}"

