#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71939 Check
  shell: grep -i PermitEmptyPasswords /etc/ssh/sshd_config
  args:
    executable: /bin/bash
  register: check1_71939
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71939 Check 2
  shell: grep -i PermitEmptyPasswords /etc/ssh/sshd_config | awk '!/^#|no/'
  args:
    executable: /bin/bash
  register: check2_71939
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71939 Report
  set_fact: 
    status_71939: "{{ 'fail' if (check2_71939.stdout != '' ) else 'pass'}}"

