#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Changed logic to check for entire audit rule string
#----------

- name: STIG RHEL7 V-72185 Check
  shell: grep -iw "/usr/sbin/pam_timestamp_check" /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_72185
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72185 Check 2
  shell: grep -iw "/usr/sbin/pam_timestamp_check" /etc/audit/audit.rules 2>/dev/null |grep -ix "\-a always,exit \-F path=/usr/sbin/pam_timestamp_check \-F auid>=1000 \-F auid!=4294967295 \-k privileged\-pam"
  args:
    executable: /bin/bash
  register: check2_72185
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72185 Report
  set_fact:
    status_72185: "{{ 'fail' if (check2_72185.stdout == '') else 'pass'}}"
