#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Changed logic to check for entire audit rule string
# Ver 3, 2019-05-28: Adjusted grep/awk combo
#----------

- name: STIG RHEL7 V-72141 Check
  shell: grep -iw /usr/sbin/setfiles /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_72141
  ignore_errors: True
  changed_when: False
  tags:
      - V-72141
      - auditrules

- name: STIG RHEL7 V-72141 Check 2
  shell: grep -iw /usr/sbin/setfiles /etc/audit/audit.rules |grep -x "\-a always,exit \-F path=/usr/sbin/setfiles \-F auid>=1000 \-F auid!=4294967295 \-k privileged\-priv_change"
  args:
    executable: /bin/bash
  register: check2_72141
  ignore_errors: True
  changed_when: False
  tags:
      - V-72141
      - auditrules


- name: STIG RHEL7 V-72141 Report
  set_fact:
    status_72141: "{{ 'fail' if (check2_72141.stdout == '' ) else 'pass'}}"
  tags:
      - V-72141
      - auditrules
