#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-20: Fixed check as to be correct.
#
#----------

- name: STIG RHEL7 V-81015 Check
  shell: grep "active" /etc/audisp/plugins.d/au-remote.conf 2>&1
  args:
    executable: /bin/bash
  register: check1_81015
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-81015 Check 2
  shell: grep "active" /etc/audisp/plugins.d/au-remote.conf |grep -ix "active = yes" 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_81015
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-81015 Report
  set_fact: 
    status_81015: "{{ 'fail' if (check2_81015.stdout == '') else 'pass'}}"

