#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-01: Modified to run script due to complexity
# Ver 3, 2019-08-15: DISA v2r4 Update JHMF
#
#----------

- name: STIG RHEL7 V-72029 Check
  shell: find `awk "-F:" '$3 > 100 && $7 !~ /false/ && $7 !~ /nologin/ && $6 !~ /\/$/ && $1 !~ /ldap/ {print $6}' /etc/passwd` -name "\.*" -ls
  args:
    executable: /bin/bash
  register: check1_72029
  ignore_errors: True
  changed_when: False
  tags:
      - V-72029
      - find
      - etcpasswd

- name: STIG RHEL7 V-72029 Check 2
  shell: for user in `awk "-F:" '$3 > 100 && $7 !~ /false/ && $7 !~ /nologin/ && $6 !~ /\/$/ && $1 !~ /ldap/  {print $1}' /etc/passwd`;do home=`grep "^$user:" /etc/passwd |awk "-F:" '{print $6}'`;group=`grep "^$user:" /etc/passwd |awk "-F:" '{print $4}'`;find $home -name '\.*' \( \( ! -user $user ! -user root \) -o ! -group $group \) -ls;done 
  args:
    executable: /bin/bash
  register: check2_72029
  ignore_errors: True
  changed_when: False
  tags:
      - V-72029
      - find
      - etcpasswd

- name: STIG RHEL7 V-72029 Report
  set_fact: 
    status_72029: "{{ 'fail' if (check2_72029.stdout != '') else 'pass'}}"
  tags:
      - V-72029
      - find
      - etcpasswd
