#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71907 Check
  shell: grep dcredit /etc/security/pwquality.conf 2>&1
  args:
    executable: /bin/bash
  register: check1_71907
  ignore_errors: True
  changed_when: False
  tags:
      - V-71907
      - pwquality

- name: STIG RHEL7 V-71907 Check 2
  shell: grep dcredit /etc/security/pwquality.conf 2>/dev/null | awk '!/^#/ && /-1/'
  args:
    executable: /bin/bash
  register: check2_71907
  ignore_errors: True
  changed_when: False
  tags:
      - V-71907
      - pwquality

- name: STIG RHEL7 V-71907 Report
  set_fact: 
    status_71907: "{{ 'fail' if (check2_71907.stdout == '' ) else 'pass'}}"
  tags:
      - V-71907
      - pwquality

