#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 3, 2019-06-18: Re-wrote yum checks to output text if package not found, per. IA.  JHMF
#
#----------

- name: STIG RHEL7 V-72305 Check
  shell: |
    yum list installed -q tftp-server 2>/dev/null
    grep server_args /etc/xinetd.d/tftp 2>/dev/null
  args:
    executable: /bin/bash
  register: check1_72305
  ignore_errors: True
  changed_when: False
  tags:
      - V-72305
      - yum

- name: STIG RHEL7 V-72305 Check 2
  shell: yum list installed -q "tftp-server" 2>&1 |egrep "tftp-server|^Error"
  args:
    executable: /bin/bash
  register: check2_72305
  ignore_errors: True
  changed_when: False
  tags:
      - V-72305
      - yum

- name: STIG RHEL7 V-72305 Check 3
  shell: grep server_args /etc/xinetd.d/tftp 2>/dev/null |grep -x "server_args = -s /var/lib/tftpboot"
  args:
    executable: /bin/bash
  register: check3_72305
  ignore_errors: True
  changed_when: False
  tags:
      - V-72305
      - yum
 
 
- name: STIG RHEL7 V-72305 Report
  set_fact: 
    status_72305: "{{ 'NA' if (check2_72305.stdout == 'Error: No matching Packages to list') else 'fail' if (check3_72305.stdout == '') else 'pass'}}"
  tags:
      - V-72305
      - yum
