#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: changed dev.null to /dev/null
# Ver 3, 2019-06-24: Added GNOME check. corrected file check. JHMF
#
#----------

- name: STIG RHEL7 V-71953 Check 1
  shell: |
     yum list installed -q gnome* 2>&1
     grep -i automaticloginenable /etc/gdm/custom.conf
  args:
    executable: /bin/bash
  ignore_errors: True
  register: check1_71953
  changed_when: False
  tags:
      - V-71953
      - yum
      - gnome

- name: STIG RHEL7 V-71953 Check 2
  shell: yum list installed -q gnome* 2>&1 |egrep "gnome|^Error"
  args:
    executable: /bin/bash
  register: check2_71953
  ignore_errors: True
  changed_when: False
  tags:
      - V-71953
      - yum
      - gnome

- name: STIG RHEL7 V-71953 Check 3
  shell:  grep -i automaticloginenable /etc/gdm/custom.conf |egrep -x "AutomaticLoginEnable=false"
  args:
    executable: /bin/bash
  register: check3_71953
  ignore_errors: True
  changed_when: False
  tags:
      - V-71953
      - yum
      - gnome

- name: STIG RHEL7 V-71953 Report
  set_fact:
    status_71953: "{{ 'NA' if (check2_71953.stdout == 'Error: No matching Packages to list') else 'fail' if (check3_71953.stdout == '') else 'pass'}}"
  tags:
      - V-71953
      - yum
      - gnome
