#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-10: added possible IP's into check
#
#----------

- name: STIG RHEL7 V-72209 Check
  shell: grep @ /etc/rsyslog.conf /etc/rsyslog.d/*.conf 2>&1
  args:
    executable: /bin/bash
  register: check1_72209
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72209 Check 2
  #shell: grep @ /etc/rsyslog.conf 2>/dev/null
  shell: egrep '^*.*[ |  ]@{1,2}[172.30.20.61|172.16.5.35|cloudIP]' /etc/rsyslog.conf 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72209
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72209 Report
  set_fact: 
    status_72209: "{{ 'fail' if (check2_72209.stdout == '') else 'pass'}}"
