#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 3, 2019-06-18: Re-wrote yum checks to output text if package not found, per. IA.  JHMF
#
#----------

- name: STIG RHEL7 V-72073 Check
  shell: |
      yum list installed -q aide 2>&1
      grep sha512 /etc/aide.conf
  args:
    executable: /bin/bash
  register: check1_72073
  ignore_errors: True
  changed_when: False
  tags:
      - V-72073
      - yum

- name: STIG RHEL7 V-72073 Check 2
  shell: yum list installed -q aide 2>&1 |egrep "aide|^Error"
  args:
    executable: /bin/bash
  register: check2_72073
  ignore_errors: True
  changed_when: False
  tags:
      - V-72073
      - yum

- name: STIG RHEL7 V-72073 Check 3
  shell: grep "^ALL " /etc/aide.conf |grep "+sha512+"
  args:
    executable: /bin/bash
  register: check3_72073
  ignore_errors: True
  changed_when: False
  tags:
      - V-72073
      - yum

- name: STIG RHEL7 V-72073 Report
  set_fact: 
    status_72073: "{{ 'fail' if (check2_72073.stdout == 'Error: No matching Packages to list') else 'fail' if (check2_72073.stdout == '') else 'pass'}}"
  tags:
      - V-72073
      - yum
