#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72001 Check
  shell: more /etc/passwd 2>&1
  args:
    executable: /bin/bash
  register: check1_72001
  ignore_errors: True
  changed_when: False
  tags:
      - V-72001
      - etcpasswd
 

- name: STIG RHEL7 V-72001 Check 2
  shell: more /etc/passwd | awk '(/games/ || /gopher/)' 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72001
  ignore_errors: True
  changed_when: False
  tags:
      - V-72001
      - etcpasswd


- name: STIG RHEL7 V-72001 Report
  set_fact: 
    status_72001: "{{ 'pass' if (check2_72001.stdout == '') else 'fail'}}"
  tags:
      - V-72001
      - etcpasswd

 

# 
