#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72049 Check
  shell: grep -i umask /home/*/.* 2>&1
  args:
    executable: /bin/bash
  register: check1_72049
  ignore_errors: True
  changed_when: False
  tags:
      - V-72049
      - other
 
- name: STIG RHEL7 V-72049 Check 2
  shell: grep -i umask /home/*/.* 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72049
  ignore_errors: True
  changed_when: False
  tags:
      - V-72049
      - other
 
- name: STIG RHEL7 V-72049 Report
  set_fact: 
    status_72049: "{{ 'pass' if (check2_72049.stdout == '') else 'fail'}}"
  tags:
      - V-72049
      - other
 
#
