#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-05-13: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 3, 2019-07-23: Better grep. JHMF

#
#----------

- name: STIG RHEL7 V-72427 Check
  shell: grep services /etc/sssd/sssd.conf /etc/sssd/conf.d/*.conf 2>&1
  args:
    executable: /bin/bash
  register: check1_72427
  ignore_errors: True
  changed_when: False
  tags:
      - V-72427
      - other

- name: STIG RHEL7 V-72427 Check 2
  shell: grep "^services = nss, pam" /etc/sssd/sssd.conf /etc/sssd/conf.d/*.conf 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72427
  ignore_errors: True
  changed_when: False
  tags:
      - V-72427
      - other

- name: STIG RHEL7 V-72427 Report
  set_fact: 
    status_72427: "{{ 'fail' if (check2_72427.stdout == '') else 'pass'}}"
  tags:
      - V-72427
      - other
