#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72003 Check
  shell: pwck -r 2>&1
  args:
    executable: /bin/bash
  register: check1_72003
  ignore_errors: True
  changed_when: False
  tags:
      - V-72003
      - other

- name: STIG RHEL7 V-72003 Check 2
  shell: pwck -r 2>/dev/null | awk '/no group/'
  args:
    executable: /bin/bash
  register: check2_72003
  ignore_errors: True
  changed_when: False
  tags:
      - V-72003
      - other

- name: STIG RHEL7 V-72003 Report
  set_fact: 
    status_72003: "{{ 'fail' if (check2_72003.stdout != '' ) else 'pass'}}"
  tags:
      - V-72003
      - other

