#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-09: Included an NA check for RHEL Systems that do not have GNOME
# Ver 3, 2019-06-18: Re-wrote yum checks to output text if package not found, per. IA.  JHMF
#
#----------

- name: STIG RHEL7 V-71893 Check 1
  shell: |
     yum list installed -q gnome* 2>&1
     echo ------
     grep -i idle-delay /etc/dconf/db/local.d/*
  args:
    executable: /bin/bash
  ignore_errors: True
  register: check1_71893
  changed_when: False
  tags:
      - V-71893
      - yum
      - gnome

- name: STIG RHEL7 V-71893 Check 2
  shell: yum list installed -q gnome* 2>&1 |egrep "gnome|^Error"
  args:
    executable: /bin/bash
  ignore_errors: True
  register: check2_71893
  changed_when: False
  tags:
      - V-71893
      - yum
      - gnome


- name: STIG RHEL7 V-71893 Check 3
  shell: grep -i "idle\-delay=uint32 900" /etc/dconf/db/local.d/* 2>/dev/null
  args:
    executable: /bin/bash
  register: check3_71893
  ignore_errors: True
  changed_when: False
  tags:
      - V-71893
      - yum
      - gnome


- name: STIG RHEL7 V-71893 Report
  set_fact: 
    status_71893: "{{ 'NA' if (check2_71893.stdout == 'Error: No matching Packages to list') else 'fail' if (check3_71893.stdout == '') else 'pass'}}"
  tags:
      - V-71893
      - yum
      - gnome
