#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 1.1, 2019-05-01: Updated to streamline 750 check.
#
#----------

- name: STIG RHEL7 V-72017 Check 1
  shell: ls -ld `cut -d":" -f1,3,6 /etc/passwd |egrep ':[0-9]{4}:'|cut -d":" -f3`
  args:
    executable: /bin/bash
  register: check1_72017
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72017 Check 2
  shell: ls -ld `cut -d":" -f1,3,6 /etc/passwd |egrep ':[0-9]{4}:'|cut -d":" -f3`|grep -v "^.....-.---"
  args:
    executable: /bin/bash
  register: check2_72017
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72017 Report
  set_fact: 
    status_72017: "{{ 'fail' if (check2_72017.stdout != '') else 'pass'}}"


