#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, Muaaz Chaudhry & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71989 Check 1
  shell: |
    ps -ef | grep -i "hipclient" | grep -v grep
    /sbin/getenforce 2>&1
  args:
    executable: /bin/bash
  register: check1_71989
  ignore_errors: True
  changed_when: False
  tags:
      - V-71989
      - selinux

- name: STIG RHEL7 V-71989 Check 2
  shell: ps -ef | grep -i "hipclient" | grep "/opt/McAfee/hip/HipClient-bin -d" |grep -v grep
  args:
    executable: /bin/bash
  register: check2_71989
  ignore_errors: True
  changed_when: False
  tags:
      - V-71989
      - selinux

- name: STIG RHEL7 V-71989 Check 3
  shell: /sbin/getenforce 2>/dev/null | awk '/Enforcing/'
  args:
    executable: /bin/bash
  register: check3_71989
  ignore_errors: True
  changed_when: False
  tags:
      - V-71989
      - selinux


- name: STIG RHEL7 V-71989 Report
  set_fact: 
    status_71989: "{{'NA' if (check2_71989.stdout != '') else 'fail' if (check3_71989.stdout == '' ) else 'pass'}}"
  tags:
      - V-71989
      - selinux

