#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-29: correct check. pipe needed before awk JHMF
#
#----------

- name: STIG RHEL7 V-72267 Check
  shell: grep -i compression /etc/ssh/sshd_config 2>&1
  args:
    executable: /bin/bash
  register: check1_72267
  ignore_errors: True
  changed_when: False
  tags:
      - V-72267
      - ssh

- name: STIG RHEL7 V-72267 Check 2
  shell: grep -i compression /etc/ssh/sshd_config 2>/dev/null |awk '!/^#/ && /delayed|no/'
  args:
    executable: /bin/bash
  register: check2_72267
  ignore_errors: True
  changed_when: False
  tags:
      - V-72267
      - ssh


- name: STIG RHEL7 V-72267 Report
  set_fact: 
    status_72267: "{{ 'fail' if (check2_72267.stdout == '' ) else 'pass'}}"
  tags:
      - V-72267
      - ssh

