#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2. 2019-06-18: Removed 'wc' usage. JHMF
#
#----------

- name: STIG RHEL7 V-71979 Check 1
  shell: grep localpkg_gpgcheck /etc/yum.conf
  args:
    executable: /bin/bash
  register: check1_71979
  ignore_errors: True
  changed_when: False
  tags:
      - V-71979
      - yum

- name: STIG RHEL7 V-71979 Check 2
  shell: grep "^localpkg_gpgcheck=1$" /etc/yum.conf
  args:
    executable: /bin/bash
  register: check2_71979
  ignore_errors: True
  changed_when: False
  tags:
      - V-71979
      - yum

- name: STIG RHEL7 V-71979 Report
  set_fact: 
    status_71979: "{{ 'fail' if (check2_71979.stdout == '') else 'pass'}}"
  tags:
      - V-71979
      - yum

