#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-79001 Check
  shell: grep -iw finit_module /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_79001
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-79001 Check 2
  shell: grep -iw finit_module /etc/audit/audit.rules 2>/dev/null |grep -ix "\-a always,exit \-F arch=b64 \-S finit_module \-k module\-change"
  args:
    executable: /bin/bash
  register: check2_79001
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-79001 Report
  set_fact: 
    status_79001: "{{ 'fail' if (check2_79001.stdout == '') else 'pass'}}"

