#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71951 Check
  shell: grep -i fail_delay /etc/login.defs
  args:
    executable: /bin/bash
  register: check1_71951
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71951 Check 2
  shell: grep -i fail_delay /etc/login.defs | awk  '!/^#/ && $2 > 3'
  args:
    executable: /bin/bash
  register: check2_71951
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71951 Report
  set_fact: 
    status_71951: "{{ 'fail' if (check2_71951.stdout == '' ) else 'pass'}}"

