#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Changed logic to check for entire audit rule string
#----------

- name: STIG RHEL7 V-72151 Check
  shell: grep -i /sbin/unix_chkpwd /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_72151
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72151 Check 2
  shell: grep -i /sbin/unix_chkpwd /etc/audit/audit.rules | awk '/unix_chkpwd -F auid>=1000 -F auid!=4294967295 -k privileged-passwd/' 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72151
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72151 Report
  set_fact:
    status_72151: "{{ 'fail' if (check2_72151.stdout == '') else 'pass'}}"
