#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72307 Check
  shell: rpm -qa | grep xorg | grep server 2>&1
  args:
    executable: /bin/bash
  register: check1_72307
  ignore_errors: True
  changed_when: False
  tags:
      - V-72307
      - yum

- name: STIG RHEL7 V-72307 Check 2
  shell: rpm -qa | grep xorg | grep server 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72307
  ignore_errors: True
  changed_when: False
  tags:
      - V-72307
      - yum

- name: STIG RHEL7 V-72307 Report
  set_fact: 
    status_72307: "{{ 'fail' if (check2_72307.stdout != '') else 'pass'}}"
  tags:
      - V-72307
      - yum

