#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 3, 2019-08-15: DISA v2r4 update. JHMF
#
#----------

- name: STIG RHEL7 V-78999 Check
  shell: |
    echo "Count the number of lines, which should be 2"
    grep -iw create_module /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_78999
  ignore_errors: True
  changed_when: False
  tags:
      - V-78999
      - auditrules

- name: STIG RHEL7 V-78999 Check 2
  shell: |
    ( grep -ix "\-a always,exit -F arch=b32 -S create_module -k module-change" /etc/audit/audit.rules
    grep -ix "\-a always,exit -F arch=b64 -S create_module -k module-change" /etc/audit/audit.rules ) |sort -u |wc -l
  args:
    executable: /bin/bash
  register: check2_78999
  ignore_errors: True
  changed_when: False
  tags:
      - V-78999
      - auditrules

- name: STIG RHEL7 V-78999 Report
  set_fact: 
    status_78999: "{{ 'fail' if (check2_78999.stdout != '2') else 'pass'}}"
  tags:
      - V-78999
      - auditrules
