#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-81021 Check
  shell:  grep "name_format" /etc/audisp/audispd.conf 2>&1
  args:
    executable: /bin/bash
  register: check1_81021
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-81021 Check 2
  shell: grep "name_format" /etc/audisp/audispd.conf 2>/dev/null | grep -i "name_format = HOSTNAME"
  args:
    executable: /bin/bash
  register: check2_81021
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-81021 Report
  set_fact: 
    status_81021: "{{ 'fail' if (check2_81021.stdout == '') else 'pass'}}"

# 