#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-21: Corrected check. JHMF
# Ver 3, 2019-06-18: Re-wrote yum checks to output text if package not found, per. IA.  JHMF
#
#----------

- name: STIG RHEL7 V-71859 Check 1
  shell: yum list installed -q gnome* 2>&1 |egrep "gnome|^Error"
  args:
    executable: /bin/bash
  ignore_errors: True
  register: check1_71859
  #ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71859 Check 2
  shell: grep ^banner-message-enable /etc/dconf/db/local.d/*
  args:
    executable: /bin/bash
  register: check2_71859
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71859 Check 3
  shell: grep ^banner-message-enable=true$ /etc/dconf/db/local.d/*
  args:
    executable: /bin/bash
  register: check3_71859
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71859 Report
  set_fact: 
    #status_71859: "{{ 'fail' if (check2_71859.stdout != '') else 'pass'}}"
    status_71859: "{{ 'NA' if (check1_71859.stdout == 'Error: No matching Packages to list') else 'fail' if (check2_71859.stdout == '') else 'fail' if (check3_71859.stdout == '') else 'pass'}}"

