#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-20: Correct grep so commented lines are not counted
# Ver 3, 2019-07-23: Added NA check. JHMF
# Ver 3, 2019-07-24: RemovedNA check lines. JHMF
#
#----------

- name: STIG RHEL7 V-71947 Check
  shell: grep -irv ^# /etc/sudoers /etc/sudoers.d/ |grep -i nopasswd
  args:
    executable: /bin/bash
  register: check1_71947
  ignore_errors: True
  changed_when: False
  tags:
      - V-71947
      - other

- name: STIG RHEL7 V-71947 Check 2
  shell: grep -irv ^# /etc/sudoers /etc/sudoers.d/ |grep -i nopasswd
  args:
    executable: /bin/bash
  register: check2_71947
  ignore_errors: True
  changed_when: False
  tags:
      - V-71947
      - other

- name: STIG RHEL7 V-71947 Report
  set_fact: 
    #status_71947: "{{ 'NA' if (check2_71947.stdout == '') else 'fail' if (check3_71947.stdout != '') else 'pass'}}"
    status_71947: "{{ 'fail' if (check2_71947.stdout != '') else 'pass'}}"
  tags:
      - V-71947
      - other

