#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-14: V2R3 updated. JHMF
# Ver 3, 2019-05-14: V2R3 updated. NHV
# Ver 3.1, 2019-05-20: DISA actual benchmark check does not match check stated in "Check Text" or "Fix Text".  Corrected so playbook will pass, like benchmark does. JHMF
# Ver 3.2, 2019-05-28: Modified check to use grep 
#----------

- name: STIG RHEL7 V-72149 Check
  shell: grep -i /usr/bin/passwd /etc/audit/audit.rules  2>&1
  args:
    executable: /bin/bash
  register: check1_72149
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72149 Check 2
  shell: grep -i /usr/bin/passwd /etc/audit/audit.rules 2>/dev/null |grep -x "\-a always,exit \-F path=/usr/bin/passwd \-F auid>=1000 \-F auid!=4294967295 \-k privileged\-passwd"
  args:
    executable: /bin/bash
  register: check2_72149
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72149 Report
  set_fact:
    status_72149: "{{ 'fail' if (check2_72149.stdout == '') else 'pass'}}"
