#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Changed logic to check for entire audit rule string
#----------

- name: STIG RHEL7 V-72177 Check
  shell:  grep -iw /usr/sbin/postqueue /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_72177
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72177 Check 2
  shell: grep -iw /usr/sbin/postqueue /etc/audit/audit.rules | awk '/postqueue -F auid>=1000 -F auid!=4294967295 -k privileged-postfix/' 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72177
  ignore_errors: True
  changed_when: False
- name: STIG RHEL7 V-72177 Report
  set_fact:
    status_72177: "{{ 'fail' if (check2_72177.stdout == '') else 'pass'}}"
