#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Modified so check1 and check2 print same output.  Result was incorrect. JHMF
#
#----------

- name: STIG RHEL7 V-71855 Check
  shell: rpm -Va | grep '^..5'  | awk '($2 != "c") {print $0}'
  args:
    executable: /bin/bash
  register: check1_71855
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71855 Check 2
  shell: rpm -Va | grep '^..5'  | awk '($2 != "c") {print $0}'
  args:
    executable: /bin/bash
  register: check2_71855
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71855 Report
  set_fact: 
    status_71855: "{{ 'fail' if (check2_71855.stdout != '') else 'pass'}}"

