#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-09: Corrected check to work.
#
#----------

- name: STIG RHEL7 V-72033 Check
  shell: find `awk "-F:" '$3 > 100 && $7 !~ /false/ && $7 !~ /nologin/ && $6 !~ /\/$/ && $1 !~ /ldap/ {print $6}' /etc/passwd` -name "\.*" -ls
  args:
    executable: /bin/bash
  register: check1_72033
  ignore_errors: True
  changed_when: False
  tags:
      - V-72033
      - find
      - etcpasswd

- name: STIG RHEL7 V-72033 Check 2
  shell: find `awk "-F:" '$3 > 100 && $7 !~ /false/ && $7 !~ /nologin/ && $6 !~ /\/$/ && $1 !~ /ldap/ {print $6}' /etc/passwd` -name "\.*" -type f -ls |grep -v " .....----- "
  args:
    executable: /bin/bash
  register: check2_72033
  ignore_errors: True
  changed_when: False
  tags:
      - V-72033
      - find
      - etcpasswd

- name: STIG RHEL7 V-72033 Report
  set_fact: 
    status_72033: "{{ 'fail' if (check2_72033.stdout != '') else 'pass'}}"
  tags:
      - V-72033
      - find
      - etcpasswd

