#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72271 Check
  shell: rule ipv4 filter IN_public_allow 0 -p tcp -m limit --limit 25/minute --limit-burst 100 -j ACCEPT 2>&1
  args:
    executable: /bin/bash
  register: check1_72271
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72271 Check 2
  shell: rule ipv4 filter IN_public_allow 0 -p tcp -m limit --limit 25/minute --limit-burst 100 -j ACCEPT | awk '/command not found/'
  args:
    executable: /bin/bash
  register: check2_72271
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72271 Report
  set_fact: 
    status_72271: "{{ 'fail' if (check2_72271.stdout != '') else 'pass'}}"

