#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-73161 Check
  shell: cat /etc/fstab | grep nfs 2>&1
  args:
    executable: /bin/bash
  register: check1_73161
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-73161 Check 2
  shell: cat /etc/fstab | grep nfs|grep -v "noexec"
  args:
    executable: /bin/bash
  register: check2_73161
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-73161 Report
  set_fact: 
    status_73161: "{{ 'fail' if (check2_73161.stdout != '') else 'pass'}}"
