#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-14: Incorporated V2R3 changes. JHMF
# Ver 2.1, 2019-05-20: Corrected logic. JHMF
#
#----------

- name: STIG RHEL7 V-71961 Check
  shell: grep -i password /boot/grub2/grub.cfg 2>&1
  args:
    executable: /bin/bash
  register: check1_71961
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71961 Check 2
  shell: grep -i "password_pbkdf2" /boot/grub2/grub.cfg 2>/dev/null |grep -v "^#" | wc -l
  args:
    executable: /bin/bash
  register: check2_71961
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71961 Check 3
  shell: grep -i "password_pbkdf2 root " /boot/grub2/grub.cfg 2>/dev/null |grep -v "^#" | wc -l
  args:
    executable: /bin/bash
  register: check3_71961
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71961 Report
  set_fact: 
    status_71961: "{{ 'fail' if (check2_71961.stdout != '1') or (check3_71961.stdout != '1') else 'pass'}}"

