#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-05-13; New check. Instudes GNOME check for NA
#
#----------

- name: STIG RHEL7 V-73155 Check 1
  shell: yum list installed -q gnome* 2>&1; grep system-db /etc/dconf/profile/user 2>&1; grep -i lock-delay /etc/dconf/db/local.d/locks/* 2>&1
  args:
    executable: /bin/bash
  ignore_errors: True
  register: check1_73155
  #ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-73155 Check 2
  shell: yum list installed -q gnome* 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_73155
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-73155 Check 3
  shell: grep system-db /etc/dconf/profile/user 2>/dev/null
  args:
    executable: /bin/bash
  register: check3_73155
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-73155 Check 4
  shell: grep -x "/org/gnome/desktop/screensaver/lock-delay" /etc/dconf/db/local.d/locks/* 2>/dev/null
  args:
    executable: /bin/bash
  register: check4_73155
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-73155 Report
  set_fact: 
    status_73155: "{{ 'NA' if (check2_73155.stdout == '') else 'fail' if ((check3_73155.stdout == '') or (check4_73155.stdout == '')) else 'pass'}}"



