#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71999 Check
  shell: yum history list
  args:
    executable: /bin/bash
  register: check1_71999
  ignore_errors: True
  changed_when: False
  tags:
      - V-71999
      - yum

- name: STIG RHEL7 V-71999 Check 2
  shell:  yum history list 2>/dev/null | awk -F '|' '$3 ~ /-/ {print $3}' | awk '{print $1}' | while read DATE; do date -d $DATE "+%s" | awk '$1 > var' var=`date --date="-30days" +%s` ; done 
  args:
    executable: /bin/bash
  register: check2_71999
  ignore_errors: True
  changed_when: False
  tags:
      - V-71999
      - yum

- name: STIG RHEL7 V-71999 Report
  set_fact: 
    status_71999: "{{ 'fail' if (check2_71999.stdout == '') else 'pass'}}"
  tags:
      - V-71999
      - yum

