#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Modified so check1 and check2 print same output.  Result was incorrect. JHMF
# Ver 3, 2019-06-18: DISA check includes only certain direcoties.  Added this into check. JHMF
# Ver 3, 2019-08-15: Check modified due to DISA V2R4 release
#
#----------

- name: STIG RHEL7 V-71855 Check
  shell: rpm -Va --noconfig | grep '^..5'  | awk '($2 != "c") {print $0}'
  args:
    executable: /bin/bash
  register: check1_71855
  ignore_errors: True
  changed_when: False
  tags:
      - V-71855
      - yum

- name: STIG RHEL7 V-71855 Check 2
  shell: rpm -Va --noconfig | grep '^..5'  | awk '($2 != "c") {print $0}' |egrep "^/usr/|^/usr/local/|^/bin/|^/sbin/|^/lib/|^/lib64/|^/libexec"
  args:
    executable: /bin/bash
  register: check2_71855
  ignore_errors: True
  changed_when: False
  tags:
      - V-71855
      - yum

- name: STIG RHEL7 V-71855 Report
  set_fact: 
    status_71855: "{{ 'fail' if (check2_71855.stdout != '') else 'pass'}}"
  tags:
      - V-71855
      - yum

