#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-14: V2R3 updates. JHMF
#
#----------

- name: STIG RHEL7 V-81009 Check
  shell: cat /etc/fstab | grep /dev/shm 2>&1; mount | grep "/dev/shm" 2>&1
  args:
    executable: /bin/bash
  register: check1_81009
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-81009 Check 2
  shell: cat /etc/fstab | grep /dev/shm |grep -v nodev 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_81009
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-81009 Check 3
  shell: mount | grep "/dev/shm" | grep nodev 2>/dev/null
  args:
    executable: /bin/bash
  register: check3_81009
  ignore_errors: True
  changed_when: False


- name: STIG RHEL7 V-81009 Report
  set_fact: 
    status_81009: "{{ 'fail' if ((check2_81009.stdout != '') or (check3_81009.stdout == '')) else 'pass'}}"

# 
