#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-05-13: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-29: Corrected checks JHMF
#
#----------

- name: STIG RHEL7 V-72293 Check
  shell: |
     grep 'net.ipv4.conf.all.send_redirects' /etc/sysctl.conf /etc/sysctl.d/* 2>&1
     echo ----------
     /sbin/sysctl -a 2>&1 | grep 'net.ipv4.conf.all.send_redirects'
  args:
    executable: /bin/bash
  register: check1_72293
  ignore_errors: True
  changed_when: False
  tags:
      - V-72293
      - sysctl

- name: STIG RHEL7 V-72293 Check 2
  shell: cat /etc/sysctl.conf /etc/sysctl.d/* 2>/dev/null |grep -x "net.ipv4.conf.all.send_redirects = 0"
  args:
    executable: /bin/bash
  register: check2_72293
  ignore_errors: True
  changed_when: False
  tags:
      - V-72293
      - sysctl

- name: STIG RHEL7 V-72293 Check 3
  shell: /sbin/sysctl -a 2>/dev/null | grep -ix "net.ipv4.conf.all.send_redirects = 0"
  args:
    executable: /bin/bash
  register: check3_72293
  ignore_errors: True
  changed_when: False
  tags:
      - V-72293
      - sysctl

- name: STIG RHEL7 V-72293 Report
  set_fact: 
    status_72293: "{{ 'fail' if ((check2_72293.stdout == '') or (check3_72293.stdout == '')) else 'pass'}}"
  tags:
      - V-72293
      - sysctl

#
