#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-21: DISA "-xdev" not completed. changed find to -prune. JHMF
#
#----------

- name: STIG RHEL7 V-72257 Check 1
  shell: find / \( -fstype nfs -prune \) -o -name ssh_host\*key -ls 2>&1
  args:
    executable: /bin/bash
  register: check1_72257
  ignore_errors: True
  changed_when: False


- name: STIG RHEL7 V-72257 Check 2
  shell: find / \( -fstype nfs -prune \) -o -name ssh_host\*key -ls 2>/dev/null |grep -v " ...-.--... "
  args:
    executable: /bin/bash
  register: check2_72257
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72257 Report
  set_fact: 
    status_72257: "{{ 'fail' if (check2_72257.stdout != '') else 'pass'}}"
