#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Changed logic to check for entire audit rule string
# Ver 2.1, 2019-05-20: fixed "AnsibleUndefinedVariable: 'status_72163' is undefined"} JHMF
#----------

- name: STIG RHEL7 V-72163 Check
  shell: grep -i "/etc/sudoers" /etc/audit/audit.rules 2>&1; grep -i "/etc/sudoers.d/" /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_72163
  ignore_errors: True
  changed_when: False
  tags:
      - V-72163
      - auditrules

- name: STIG RHEL7 V-72163 Check 2
  shell: grep -i "/etc/sudoers" /etc/audit/audit.rules 2>/dev/null |grep -ix "\-w /etc/sudoers \-p wa \-k privileged\-actions"
  args:
    executable: /bin/bash
  register: check2_72163
  ignore_errors: True
  changed_when: False
  tags:
      - V-72163
      - auditrules

- name: STIG RHEL7 V-72163 Check 3
  shell: grep -i "/etc/sudoers.d/" /etc/audit/audit.rules 2>/dev/null |grep -ix "\-w /etc/sudoers.d/ \-p wa \-k privileged\-actions"
  args:
    executable: /bin/bash
  register: check3_72163
  ignore_errors: True
  changed_when: False
  tags:
      - V-72163
      - auditrules

- name: STIG RHEL7 V-72163 Report
  set_fact:
    status_72163: "{{ 'fail' if ((check2_72163.stdout == '') or (check3_72163.stdout == '')) else 'pass'}}"
  tags:
      - V-72163
      - auditrules
