#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72079 Check
  shell: systemctl is-active auditd.service 2>&1
  args:
    executable: /bin/bash
  register: check1_72079
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72079 Check 2
  shell: systemctl is-active auditd.service 2>/dev/null | awk '!/^active/'
  args:
    executable: /bin/bash
  register: check2_72079
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72079 Report
  set_fact: 
    status_72079: "{{ 'fail' if (check2_72079.stdout != '' ) else 'pass'}}"

