#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-14: Added manually complet statement
#
#----------

- name: STIG RHEL7 V-72219 Check
  shell: echo -e "This check will need to be manually completed.\n"; \
        firewall-cmd --list-all 2>&1
  args:
    executable: /bin/bash
  register: check1_72219
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72219 Check 2
  shell: firewall-cmd --list-all 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72219
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72219 Report
  set_fact: 
    #status_72219: "{{ 'fail' if (check2_72219.stdout == '') else 'pass'}}"
    status_72219: 'NR'

