#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72313 Check
  shell: if [ "$(ls -al /etc/snmp/snmpd.conf 2>/dev/null)" ]; then awk '/public|private/' /etc/snmp/snmpd.conf; fi
  args:
    executable: /bin/bash
  register: check1_72313
  ignore_errors: True
  changed_when: False
  tags:
      - V-72313
      - other

- name: STIG RHEL7 V-72313 Check 2
  shell: if [ "$(ls -al /etc/snmp/snmpd.conf 2>/dev/null)" ]; then awk '/public|private/' /etc/snmp/snmpd.conf; fi
  args:
    executable: /bin/bash
  register: check2_72313
  ignore_errors: True
  changed_when: False
  tags:
      - V-72313
      - other


- name: STIG RHEL7 V-72313 Report
  set_fact: 
    status_72313: "{{ 'fail' if (check2_72313.stdout != '' ) else 'pass'}}"
  tags:
      - V-72313
      - other

