#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Changed logic to check for entire audit rule string
#----------

- name: STIG RHEL7 V-72187 Check
  shell: grep -iw init_module /etc/audit/audit.rules
  args:
    executable: /bin/bash
  register: check1_72187
  ignore_errors: True
  changed_when: False
  tags:
      - V-72187
      - auditrules

- name: STIG RHEL7 V-72187 Check 2
  shell: grep -iw init_module /etc/audit/audit.rules | awk '/-a always,exit -F arch=b64 -S init_module -k module-change'/ 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72187
  ignore_errors: True
  changed_when: False
  tags:
      - V-72187
      - auditrules
- name: STIG RHEL7 V-72187 Report
  set_fact:
    status_72187: "{{ 'fail' if (check2_72187.stdout == '') else 'pass'}}"
  tags:
      - V-72187
      - auditrules
