#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-07-24: added HBSS check
# Ver 3, 2019-08-15: DISA v2r4 check update
#
#----------

- name: STIG RHEL7 V-71983 Check
  shell: |
    rpm -qa | grep MFEhiplsm
    ps -ef | grep -i "hipclient" |grep -v grep
    grep -ir usb-storage /etc/modprobe.d 2>&1
  args:
    executable: /bin/bash
  register: check1_71983
  ignore_errors: True
  changed_when: False
  tags:
      - V-71983
      - modprobe

- name: STIG RHEL7 V-71983 Check 2
  shell: rpm -qa | grep MFEhiplsm 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_71983
  ignore_errors: True
  changed_when: False
  tags:
      - V-71983
      - modprobe

- name: STIG RHEL7 V-71983 Check 3
  shell: ps -ef | grep -i "hipclient" 2>/dev/null |grep -v grep
  args:
    executable: /bin/bash
  register: check3_71983
  ignore_errors: True
  changed_when: False
  tags:
      - V-71983
      - modprobe


- name: STIG RHEL7 V-71983 Check 4
  shell: egrep -irx "install usb-storage /bin/true" /etc/modprobe.d 2>/dev/null
  args:
    executable: /bin/bash
  register: check4_71983
  ignore_errors: True
  changed_when: False
  tags:
      - V-71983
      - modprobe

- name: STIG RHEL7 V-71983 Check 5
  shell: egrep -irx "blacklist usb-storage" /etc/modprobe.d 2>/dev/null
  args:
    executable: /bin/bash
  register: check5_71983
  ignore_errors: True
  changed_when: False
  tags:
      - V-71983
      - modprobe

- name: STIG RHEL7 V-71983 Report
  set_fact: 
    status_71983: "{{ 'NA' if ((check2_71983.stdout != '') and (check3_71983.stdout != '')) else 'fail' if ((check4_71983.stdout == '') or (check5_71983.stdout == '')) else 'pass'}}"
  tags:
      - V-71983
      - modprobe
