#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72311 Check
  shell: cat /etc/fstab | grep nfs 2>&1
  args:
    executable: /bin/bash
  register: check1_72311
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72311 Check 2
  shell: cat /etc/fstab | grep nfs|grep -v "sec=sys:krb5:krb5i:krb5p"
  args:
    executable: /bin/bash
  register: check2_72311
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72311 Report
  set_fact: 
    status_72311: "{{ 'fail' if (check2_72311.stdout != '') else 'pass'}}"
