#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Changed logic to check for entire audit rule string
#----------

- name: STIG RHEL7 V-72199 Check
  shell: grep -iw rename /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_72199
  ignore_errors: True
  changed_when: False
  tags:
      - V-72199
      - auditrules

- name: STIG RHEL7 V-72199 Check 2
  shell: grep -iw rename /etc/audit/audit.rules | awk '/-a always,exit -F arch=b64 -S rename -F auid>=1000 -F auid!=4294967295 -k delete/' 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72199
  ignore_errors: True
  changed_when: False
  tags:
      - V-72199
      - auditrules


- name: STIG RHEL7 V-72199 Report
  set_fact:
    status_72199: "{{ 'fail' if (check2_72199.stdout == '' ) else 'pass'}}"
  tags:
      - V-72199
      - auditrules
