#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-92255 Check
  shell: echo -e "Checking if SELINUX is in use\n"; /sbin/getenforce 2>&1
  args:
    executable: /bin/bash
  register: check1_92255
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-92255 Check 2
  shell: /sbin/getenforce 2>/dev/null | awk '/Enforcing/'
  args:
    executable: /bin/bash
  register: check2_92255
  ignore_errors: True
  changed_when: False


- name: STIG RHEL7 V-92255 Report
  set_fact: 
    status_92255: "{{ 'fail' if (check2_92255.stdout == '' ) else 'pass'}}"

