#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71985 Check
  shell: systemctl status autofs 2>&1
  args:
    executable: /bin/bash
  register: check1_71985
  ignore_errors: True
  changed_when: False
  tags:
      - V-71985
      - systemctl

- name: STIG RHEL7 V-71985 Check 2
  shell: systemctl status autofs 2>&1 | awk '/inactive|could not be found/'
  args:
    executable: /bin/bash
  register: check2_71985
  ignore_errors: True
  changed_when: False
  tags:
      - V-71985
      - systemctl

- name: STIG RHEL7 V-71985 Report
  set_fact: 
    status_71985: "{{ 'fail' if (check2_71985.stdout == '' ) else 'pass'}}"
  tags:
      - V-71985
      - systemctl

