#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-05-13: added check JHMF
#----------

- name: STIG RHEL7 V-73173 Check
  shell: grep /etc/security/opasswd /etc/audit/audit.rules 2>&1 
  args:
    executable: /bin/bash
  register: check1_73173
  ignore_errors: True
  changed_when: False
  tags:
      - V-73173
      - auditrules

- name: STIG RHEL7 V-73173 Check 2
  shell: grep -x "\-w /etc/security/opasswd \-p wa \-k identity" /etc/audit/audit.rules 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_73173
  ignore_errors: True
  changed_when: False
  tags:
      - V-73173
      - auditrules

- name: STIG RHEL7 V-73173 Report
  set_fact:
    status_73173: "{{ 'fail' if (check2_73173.stdout == '' ) else 'pass'}}"
  tags:
      - V-73173
      - auditrules
