#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72253 Check
  shell: grep -i macs /etc/ssh/sshd_config 2>&1
  args:
    executable: /bin/bash
  register: check1_72253
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72253 Check 2
  shell: grep -i macs /etc/ssh/sshd_config 3>/dev/null | awk '!/^#/ && /hmac-sha2-256|hmac-sha2-512/'
  args:
    executable: /bin/bash
  register: check2_72253
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72253 Report
  set_fact: 
    status_72253: "{{ 'fail' if (check2_72253.stdout == '') else 'pass'}}"

