#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-09: Added find instead of stat JHMF
#
#----------

- name: STIG RHEL7 V-72055 Check 1
  shell: find /etc/cron.allow -type f -ls 2>&1
  args:
    executable: /bin/bash
  register: check1_72055
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72055 Check 2
  shell: find /etc/cron.allow -type f ! -group root -ls 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72055
  ignore_errors: True
  changed_when: False

#- name: STIG RHEL7 V-72055 Check 2
#  stat: path="/etc/cron.allow"
#  register: check2_72055
#  ignore_errors: True
#  changed_when: False

#- name: STIG RHEL7 V-72055 NA
#  when: (check2_72055.stat.exists == false )
#  set_fact: 
#    status_72055: "NA"


- name: STIG RHEL7 V-72055 Report
  ignore_errors: True
  #when: (check2_72055.stat.exists == "true" )
  set_fact: 
    status_72055: "{{ 'fail' if (check2_72055.stdout != '') else 'pass'}}"

