#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-09: rewrite so check can be debugged, if needed
# Ver 3, 2019-05-31: changed check2 for performance. Large number of  o+w files would timeout ssh connection.
#
#----------

- name: STIG RHEL7 V-72037 Check
  shell: |
     find / \( -fstype nfs -o -fstype proc -o -fstype cgroup \) -prune -o -perm -002 -type f -print |tee /tmp/V-72037
     find `awk "-F:" '$3 > 100 && $7 !~ /false/ && $7 !~ /nologin/ && $6 !~ /\/$/ && $1 !~ /ldap/ {print $6}' /etc/passwd` -name "\.*" -type f -print |tee /tmp/V-72037-2
  args:
    executable: /bin/bash
  register: check1_72037
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72037 Check 2
  shell:  for i in `cat /tmp/V-72037`;do grep -ir $i `cat /tmp/V-72037-2|grep -v .bash_history`;done
  args:
    executable: /bin/bash
  register: check2_72037
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72037 Report
  set_fact: 
    status_72037: "{{ 'fail' if (check2_72037.stdout != '') else 'pass'}}"

