#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-05-13: added check
#----------

- name: STIG RHEL7 V-73171 Check
  shell: grep /etc/shadow /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_73171
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-73171 Check 2
  shell: grep -x "\-w /etc/shadow \-p wa \-k identity" /etc/audit/audit.rules 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_73171
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-73171 Report
  set_fact:
    status_73171: "{{ 'fail' if (check2_73171.stdout == '' ) else 'pass'}}"
