#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-92255 Check
  shell: |
     /sbin/getenforce 2>&1
     rpm -qa | grep MFEhiplsm 2>&1
     ps -ef | grep -i "hipclient"

  args:
    executable: /bin/bash
  register: check1_92255
  ignore_errors: True
  changed_when: False
  tags:
      - V-92255
      - hips

- name: STIG RHEL7 V-92255 Check 2
  shell: rpm -qa 2>/dev/null | grep MFEhiplsm |grep -v grep
  args:
    executable: /bin/bash
  register: check2_92255
  ignore_errors: True
  changed_when: False
  tags:
      - V-92255
      - hips

- name: STIG RHEL7 V-92255 Check 3
  shell: ps -ef 2>/dev/null | grep -i "hipclient" |grep -v grep 
  args:
    executable: /bin/bash
  register: check3_92255
  ignore_errors: True
  changed_when: False
  tags:
      - V-92255
      - hips



- name: STIG RHEL7 V-92255 Report
  set_fact: 
    status_92255: "{{ 'fail' if ((check2_92255.stdout == '' ) or (check3_92255.stdout == '' )) else 'pass'}}"
  tags:
      - V-92255
      - hips

