#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71955 Check
  shell: if [ "$(cat /etc/gdm/custom.conf 2>/dev/null)" ]; then grep -i timedloginenable /etc/gdm/custom.conf; else echo "GNOME is not installed"; fi
  args:
    executable: /bin/bash
  register: check1_71955
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71955 Check 2
  shell: if [ "$(cat /etc/gdm/custom.conf 2>/dev/null)" ]; then grep -i timedloginenable /etc/gdm/custom.conf; fi
  args:
    executable: /bin/bash
  register: check2_71955
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71955 Report
  set_fact: 
    status_71955: "{{ 'fail' if (check2_71955.stdout != '' ) else 'pass'}}"

