#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71903 Check
  shell: grep ucredit /etc/security/pwquality.conf 2>&1
  args:
    executable: /bin/bash
  register: check1_71903
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71903 Check 2
  shell: grep ucredit /etc/security/pwquality.conf | awk '!/^#/ && /-1/'
  args:
    executable: /bin/bash
  register: check2_71903
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-71903 Report
  set_fact: 
    status_71903: "{{ 'fail' if (check2_71903.stdout == '' ) else 'pass'}}"

