#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71921 Check
  shell: grep -i encrypt /etc/login.defs 2>&1
  args:
    executable: /bin/bash
  register: check1_71921
  ignore_errors: True
  changed_when: False
  tags:
      - V-71921
      - logindefs

- name: STIG RHEL7 V-71921 Check 2
  shell: grep -i encrypt /etc/login.defs 2>/dev/null | awk '!/^#/ && /SHA512/'
  args:
    executable: /bin/bash
  register: check2_71921
  ignore_errors: True
  changed_when: False
  tags:
      - V-71921
      - logindefs

- name: STIG RHEL7 V-71921 Report
  set_fact: 
    status_71921: "{{ 'fail' if (check2_71921.stdout == '' ) else 'pass'}}"
  tags:
      - V-71921
      - logindefs

