#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-10: modified check JHMF
#
#----------

- name: STIG RHEL7 V-72223 Check
  #shell: grep -i tmout /etc/bashrc 2>&1
  shell: grep -i tmout /etc/profile.d/*
  args:
    executable: /bin/bash
  register: check1_72223
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72223 Check 2
  shell: egrep -i "tmout=600|readonly TMOUT|export TMOUT" /etc/profile.d/* 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72223
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72223 Report
  set_fact: 
    status_72223: "{{ 'fail' if (check2_72223.stdout == '' ) else 'pass'}}"

