#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-07-26: Reviewed and corrected. JHMF
#
#----------

- name: STIG RHEL7 V-71915 Check
  shell: grep maxrepeat /etc/security/pwquality.conf 2>&1
  args:
    executable: /bin/bash
  register: check1_71915
  ignore_errors: True
  changed_when: False
  tags:
      - V-71915
      - pwquality

- name: STIG RHEL7 V-71915 Check 2
  shell: grep maxrepeat /etc/security/pwquality.conf 2>/dev/null | egrep -x "maxrepeat = [1|2|3]"
  args:
    executable: /bin/bash
  register: check2_71915
  ignore_errors: True
  changed_when: False
  tags:
      - V-71915
      - pwquality

- name: STIG RHEL7 V-71915 Report
  set_fact: 
    status_71915: "{{ 'fail' if (check2_71915.stdout == '' ) else 'pass'}}"
  tags:
      - V-71915
      - pwquality

