#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-07-26: Reviewed. JHMF
#
#----------

- name: STIG RHEL7 V-71945 Check 1
  shell: grep pam_faillock.so /etc/pam.d/password-auth /etc/pam.d/system-auth
  args:
    executable: /bin/bash
  register: check1_71945
  ignore_errors: True
  changed_when: False
  tags:
      - V-71945
      - pam

- name: STIG RHEL7 V-71945 Check 2
  shell: egrep -x "auth +required +pam_faillock.so +preauth +silent +audit +deny=3 +even_deny_root +fail_interval=900 +unlock_time=604800|auth +sufficient +pam_unix.so +try_first_pass|auth +\[default=die\] +pam_faillock.so +authfail +audit +deny=3 +even_deny_root +fail_interval=900 +unlock_time=604800|account +required +pam_faillock.so" /etc/pam.d/password-auth /etc/pam.d/system-auth
  args:
    executable: /bin/bash
  register: check2_71945
  ignore_errors: True
  changed_when: False
  tags:
      - V-71945
      - pam

- name: STIG RHEL7 V-71945 Check 3
  shell: egrep -x "auth +required +pam_faillock.so +preauth +silent +audit +deny=3 +even_deny_root +fail_interval=900 +unlock_time=604800|auth +sufficient +pam_unix.so +try_first_pass|auth +\[default=die\] +pam_faillock.so +authfail +audit +deny=3 +even_deny_root +fail_interval=900 +unlock_time=604800|account +required +pam_faillock.so" /etc/pam.d/password-auth /etc/pam.d/system-auth|wc -l
  args:
    executable: /bin/bash
  register: check3_71945
  ignore_errors: True
  changed_when: False
  tags:
      - V-71945
      - pam

- name: STIG RHEL7 V-71945 Report
  set_fact: 
    status_71945: "{{ 'fail' if (check3_71945.stdout != '8' ) else 'pass'}}"
  tags:
      - V-71945
      - pam
