#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71949 Check
  shell: grep -i authenticate /etc/sudoers /etc/sudoers.d/*  2>&1
  args:
    executable: /bin/bash
  register: check1_71949
  ignore_errors: True
  changed_when: False
  tags:
      - V-71949
      - other

- name: STIG RHEL7 V-71949 Check 2
  shell: grep -i authenticate /etc/sudoers /etc/sudoers.d/*  2>/dev/null | awk '/!authenticate/'
  args:
    executable: /bin/bash
  register: check2_71949
  ignore_errors: True
  changed_when: False
  tags:
      - V-71949
      - other


- name: STIG RHEL7 V-71949 Report
  set_fact: 
    status_71949: "{{ 'fail' if (check2_71949.stdout != '' ) else 'pass'}}"
  tags:
      - V-71949
      - other


