#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 3, 2019-06-18: Re-wrote yum checks to output text if package not found, per. IA.  JHMF
#
#----------

- name: STIG RHEL7 V-72317 Check
  shell: yum list installed libreswan 2>&1
  args:
    executable: /bin/bash
  register: check1_72317
  ignore_errors: True
  changed_when: False
  tags:
      - V-72317
      - yum

- name: STIG RHEL7 V-72317 Check 2
  shell: yum list installed -q libreswan 2>&1 |egrep "libreswan|^Error"
  args:
    executable: /bin/bash
  register: check2_72317
  ignore_errors: True
  changed_when: False
  tags:
      - V-72317
      - yum

- name: STIG RHEL7 V-72317 Report
  set_fact: 
    status_72317: "{{ 'fail' if (check2_72317.stdout != 'Error: No matching Packages to list') else 'pass'}}"
  tags:
      - V-72317
      - yum
