#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71987 Check
  shell: grep -i clean_requirements_on_remove /etc/yum.conf  2>&1
  args:
    executable: /bin/bash
  register: check1_71987
  ignore_errors: True
  changed_when: False
  tags:
      - V-71987
      - yum

- name: STIG RHEL7 V-71987 Check 2
  shell: grep -i "^clean_requirements_on_remove=1$" /etc/yum.conf  2>/dev/null
  args:
    executable: /bin/bash
  register: check2_71987
  ignore_errors: True
  changed_when: False
  tags:
      - V-71987
      - yum


- name: STIG RHEL7 V-71987 Report
  set_fact: 
    status_71987: "{{ 'fail' if (check2_71987.stdout == '' ) else 'pass'}}"
  tags:
      - V-71987
      - yum

