#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-05-06
#
# Change History:
#
# Ver 1, 2019-05-06: Baseline, based on DISA RHEL7 STIGS v2r2.
# 
#----------

- name: STIG RHEL7 V-72093 Check
  shell: grep -i action_mail_acct /etc/audit/auditd.conf 2>&1
  args:
    executable: /bin/bash
  register: check1_72093
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72093 Check 2
  shell: grep -i action_mail_acct /etc/audit/auditd.conf | awk '/^action_mail_acct = root/' 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72093
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72093 Report
  set_fact:
    status_72093: "{{ 'fail' if (check2_72093.stdout == '') else 'pass'}}"
