#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-05-13; New check. Instudes GNOME check for NA
# Ver 3, 2019-06-18: Re-wrote yum checks to output text if package not found, per. IA.  JHMF
#
#----------

- name: STIG RHEL7 V-77819 Check 1
  shell: yum list installed -q gnome* 2>&1; grep system-db /etc/dconf/profile/user 2>&1; grep enable-smartcard-authentication /etc/dconf/db/local.d/* 2>&1
  args:
    executable: /bin/bash
  ignore_errors: True
  register: check1_77819
  #ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-77819 Check 2
  shell: yum list installed -q gnome* 2>&1 |egrep "gnome|^Error"
  args:
    executable: /bin/bash
  register: check2_77819
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-77819 Check 3
  shell: grep system-db /etc/dconf/profile/user 2>/dev/null
  args:
    executable: /bin/bash
  register: check3_77819
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-77819 Check 4
  shell: grep -x "enable-smartcard-authentication=true" /etc/dconf/db/local.d/locks/* 2>/dev/null
  args:
    executable: /bin/bash
  register: check4_77819
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-77819 Report
  set_fact: 
    status_77819: "{{ 'NA' if (check2_77819.stdout == 'Error: No matching Packages to list') else 'fail' if ((check3_77819.stdout == '') or (check4_77819.stdout == '')) else 'pass'}}"

