#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72231 Check
  shell: |
      echo -e "\n    grep -i useldapauth /etc/sysconfig/authconfig 2>&1"; grep -i useldapauth /etc/sysconfig/authconfig 2>&1; \
      echo -e "\n    grep -i cacertfile /etc/pam_ldap.conf"; grep -i cacertfile /etc/pam_ldap.conf; 
  args:
    executable: /bin/bash
  register: check1_72231
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72231 Check 2
  shell: grep -i useldapauth /etc/sysconfig/authconfig 2>/dev/null | awk '/USELDAPAUTH=yes/'
  args:
    executable: /bin/bash
  register: check2_72231
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72231 Check 3
  shell: grep -i cacertfile /etc/pam_ldap.conf | awk '/tls_cacertfile/'
  args:
    executable: /bin/bash
  register: check3_72231
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72231 Report
  set_fact: 
    status_72231: "{{ 'fail' if ((check2_72231.stdout != '' and check3_72231.stdout == '' )) else 'pass'}}"

