#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-06-06: Content was for a different check, rewrote to Baseline
#----------

- name: STIG RHEL7 V-72095 Check
  shell: grep -iw execve /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_72095
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72095 Check 2
  shell: grep -iw execve /etc/audit/audit.rules | awk '/execve/' 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72095
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72095 Report
  set_fact:
    status_72095: "{{ 'fail' if (check2_72095.stdout == '') else 'pass'}}"
