#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72069 Check
  shell: |
      echo -e "\n    yum list installed aide"; yum list installed aide; \
      echo -e "\n    AIDE_CONF=`find / -xdev -name aide.conf`; echo $AIDE_CONF"; AIDE_CONF=`find / -xdev -name aide.conf`; echo $AIDE_CONF; \
      echo -e "\n    awk '/^ALL /' $AIDE_CONF"; awk '/^ALL /' $AIDE_CONF; 2>&1
  args:
    executable: /bin/bash
  register: check1_72069
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72069 Check 2
  shell: yum list installed aide 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72069
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72069 Check 3
  shell: AIDE_CONF=`find / -xdev -name aide.conf`; awk '/^ALL /' $AIDE_CONF | awk '/acl/'
  args:
    executable: /bin/bash
  register: check3_72069
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72069 Report
  set_fact: 
    status_72069: "{{ 'fail' if (check3_72069.stdout == '') else 'pass'}}"
