#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72005 Check
  shell: awk "-F:" '$3 == 0 {print $1}' /etc/passwd 2>&1
  args:
    executable: /bin/bash
  register: check1_72005
  ignore_errors: True
  changed_when: False
  tags:
      - V-72005
      - etcpasswd

- name: STIG RHEL7 V-72005 Check 2
  shell: awk "-F:" '$3 == 0 {print $1}' /etc/passwd 2>/dev/null | awk '!/root/'
  args:
    executable: /bin/bash
  register: check2_72005
  ignore_errors: True
  changed_when: False
  tags:
      - V-72005
      - etcpasswd


- name: STIG RHEL7 V-72005 Report
  set_fact: 
    status_72005: "{{ 'fail' if (check2_72005.stdout != '' ) else 'pass'}}"
  tags:
      - V-72005
      - etcpasswd
