#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
# Ver 2, 2019-05-09: Included a check for CREATE_HOME and yes for /etc/login.defs
#----------

- name: STIG RHEL7 V-72013 Check
  shell: grep -i create_home /etc/login.defs 2>&1
  args:
    executable: /bin/bash
  register: check1_72013
  ignore_errors: True
  changed_when: False
  tags:
      - V-72013
      - logindefs

- name: STIG RHEL7 V-72013 Check 2
  # tab between HOME and yes
  # Required && instead of tab
  shell: grep -i create_home /etc/login.defs 2>/dev/null | awk '/CREATE_HOME/&&/yes/'
  args:
    executable: /bin/bash
  register: check2_72013
  ignore_errors: True
  changed_when: False
  tags:
      - V-72013
      - logindefs

- name: STIG RHEL7 V-72013 Report
  set_fact: 
    status_72013: "{{ 'fail' if (check2_72013.stdout == '' ) else 'pass'}}"
  tags:
      - V-72013
      - logindefs

