#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-09: added modprobe check
#
#----------

- name: STIG RHEL7 V-72043 Check
  shell: echo "`more /etc/fstab 2>&1` ------------ `grep -ri usb /etc/modprobe* 2>&1`"
  args:
    executable: /bin/bash
  register: check1_72043
  ignore_errors: True
  changed_when: False
 
- name: STIG RHEL7 V-72043 Check 2
  shell: more /etc/fstab | awk '( /usbflash/ || /removable/)' 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72043
  ignore_errors: True
  changed_when: False
 
- name: STIG RHEL7 V-72043 Check 3
  shell: grep -ri "^install usb-storage /bin/true$" /etc/modprobe.d/* 2>/dev/null
  args:
    executable: /bin/bash
  register: check3_72043
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72043 Report
  set_fact: 
    status_72043: "{{ 'pass' if ((check2_72043.stdout == '') and (check3_72043.stdout != '')) else 'fail'}}"

