#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71983 Check
  shell: grep -ir usb-storage /etc/modprobe.d/* 2>&1
  args:
    executable: /bin/bash
  register: check1_71983
  ignore_errors: True
  changed_when: False
  tags:
      - V-71983
      - modprobe

- name: STIG RHEL7 V-71983 Check 2
  shell: grep -ir "^install usb-storage /bin/true$" /etc/modprobe.d*
  args:
    executable: /bin/bash
  register: check2_71983
  ignore_errors: True
  changed_when: False
  tags:
      - V-71983
      - modprobe

- name: STIG RHEL7 V-71983 Report
  set_fact: 
    status_71983: "{{ 'fail' if (check2_71983.stdout == '') else 'pass'}}"
  tags:
      - V-71983
      - modprobe

