#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-28: Added OS version check.
#
#----------

- name: STIG RHEL7 V-72251 Check
  shell: |
     cat /etc/redhat-release
     grep -i protocol /etc/ssh/sshd_config 2>&1
  args:
    executable: /bin/bash
  register: check1_72251
  ignore_errors: True
  changed_when: False
  tags:
      - V-72251
      - ssh
      - redhatrelease

- name: STIG RHEL7 V-72251 Check 2
  shell: grep " 7.[0-3] " /etc/redhat-release
  args:
    executable: /bin/bash
  register: check2_72251
  ignore_errors: True
  changed_when: False
  tags:
      - V-72251
      - ssh
      - redhatrelease

- name: STIG RHEL7 V-72251 Check 3
  shell: grep -i protocol /etc/ssh/sshd_config 2>/dev/null | awk '/^Protocol 2/'
  args:
    executable: /bin/bash
  register: check3_72251
  ignore_errors: True
  changed_when: False
  tags:
      - V-72251
      - ssh
      - redhatrelease


- name: STIG RHEL7 V-72251 Report
  set_fact: 
    status_72251: "{{ 'NA' if check2_72251.stdout == '' else 'fail' if (checks32_72251.stdout == '' ) else 'pass'}}"
  tags:
      - V-72251
      - ssh
      - redhatrelease


