#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-29: Corrected check to DISA check specs. JHMF
#
#----------

- name: STIG RHEL7 V-72275 Check
  shell: grep pam_lastlog /etc/pam.d/postlogin
  args:
    executable: /bin/bash
  register: check1_72275
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72275 Check 2
  shell: grep pam_lastlog /etc/pam.d/postlogin |egrep "^session +required +pam_lastlog.so +showfailed"
  args:
    executable: /bin/bash
  register: check2_72275
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72275 Report
  set_fact: 
    status_72275: "{{ 'fail' if (check2_72275.stdout == '') else 'pass'}}"

