#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-17: Changed logic to check for entire audit rule string
# Ver 3.1, 2019-05-20: DISA actuall benchmark check does not match check stated in "Check Text" or "Fix Text".  Corrected so playbook will pass, like benchmark does. JHMF
#----------

- name: STIG RHEL7 V-72167 Check
  shell: grep -i /usr/bin/chsh /etc/audit/audit.rules 2>&1
  args:
    executable: /bin/bash
  register: check1_72167
  ignore_errors: True
  changed_when: False
  tags:
      - V-72167
      - auditrules

- name: STIG RHEL7 V-72167 Check 2
  shell: grep -i /usr/bin/chsh /etc/audit/audit.rules 2>/dev/null |grep -ix "\-a always,exit \-F path=/usr/bin/chsh \-F auid>=1000 \-F auid!=4294967295 \-k privileged\-priv_change"
  args:
    executable: /bin/bash
  register: check2_72167
  ignore_errors: True
  changed_when: False
  tags:
      - V-72167
      - auditrules

- name: STIG RHEL7 V-72167 Report
  set_fact:
    status_72167: "{{ 'fail' if (check2_72167.stdout == '') else 'pass'}}"
  tags:
      - V-72167
      - auditrules
