#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-09: added find instead of stst
#
#----------

- name: STIG RHEL7 V-72053 Check 1
  shell: find /etc/cron.allow -type f -ls 2>&1
  args:
    executable: /bin/bash
  register: check1_72053
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72053 Check 2
  shell: find /etc/cron.allow -type f ! -user root -ls 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72053
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72053 Report
  ignore_errors: True
  #when: (check2_72053.stat.exists == "true" )
  set_fact: 
    status_72053: "{{ 'fail' if (check2_72053.stdout != '') else 'pass'}}"

