#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-05-13; New check. JHMF
#
#----------

- name: STIG RHEL7 V-81003 Check 1
  shell: cat /etc/pam.d/passwd | grep -i substack | grep -i system-auth 2>&1
  args:
    executable: /bin/bash
  ignore_errors: True
  register: check1_81003
  #ignore_errors: True
  changed_when: False
  tags:
      - V-81003
      - pam

- name: STIG RHEL7 V-81003 Check 2
  shell: cat /etc/pam.d/passwd | grep -i ^password |grep -i substack | grep -i system-auth$ 2>&1
  args:
    executable: /bin/bash
  register: check2_81003
  ignore_errors: True
  changed_when: False
  tags:
      - V-81003
      - pam

- name: STIG RHEL7 V-81003 Report
  set_fact: 
    status_81003: "{{ 'fail' if (check2_81003.stdout == '') else 'pass'}}"
  tags:
      - V-81003
      - pam

