#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-08: Modied to include better check & mirror 72017 check
#
#----------

- name: STIG RHEL7 V-72027 Check
  shell: ls -ld `cut -d":" -f1,3,6 /etc/passwd |egrep ':[0-9]{4}:'|cut -d":" -f3`
  args:
    executable: /bin/bash
  register: check1_72027
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72027 Check 2
  shell: find `cut -d":" -f1,3,6 /etc/passwd |egrep ':[0-9]{4}:'|cut -d":" -f3` -ls|grep -v " .....-.--- "
  args:
    executable: /bin/bash
  register: check2_72027
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72027 Report
  set_fact: 
    status_72027: "{{ 'fail' if (check2_72027.stdout != '') else 'pass'}}"


