#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72011 Check
  shell: cut "-d:" -f 1,3,6 /etc/passwd  | awk "-F:" '$2 > 1000 && $2 < 64999 { print $3}' | while read DIR; do ls -ld $DIR 2>&1; done
  args:
    executable: /bin/bash
  register: check1_72011
  ignore_errors: True
  changed_when: False
  tags:
      - V-72011
      - etcpasswd

- name: STIG RHEL7 V-72011 Check 2
  shell: cut "-d:" -f 1,3,6 /etc/passwd  | awk "-F:" '$2 > 1000 && $2 < 64999 { print $3}' | while read DIR; do ls -ld $DIR 2>&1; done | awk '/No such file or directory/'
  args:
    executable: /bin/bash
  register: check2_72011
  ignore_errors: True
  changed_when: False
  tags:
      - V-72011
      - etcpasswd

- name: STIG RHEL7 V-72011 Report
  set_fact: 
    status_72011: "{{ 'fail' if (check2_72011.stdout != '') else 'pass'}}"
  tags:
      - V-72011
      - etcpasswd
