#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-07-26: Reviewed. JHMF
#
#----------

- name: STIG RHEL7 V-71937 Check
  shell: grep nullok /etc/pam.d/system-auth-ac 2>&1
  args:
    executable: /bin/bash
  register: check1_71937
  ignore_errors: True
  changed_when: False
  tags:
      - V-71937
      - pam

- name: STIG RHEL7 V-71937 Check 2
  shell: grep nullok /etc/pam.d/system-auth-ac 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_71937
  ignore_errors: True
  changed_when: False
  tags:
      - V-71937
      - pam


- name: STIG RHEL7 V-71937 Report
  set_fact: 
    status_71937: "{{ 'fail' if (check2_71937.stdout != '' ) else 'pass'}}"
  tags:
      - V-71937
      - pam

