#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71991 Check
  shell: /sbin/sestatus 2>&1
  args:
    executable: /bin/bash
  register: check1_71991
  ignore_errors: True
  changed_when: False
  tags:
      - V-71991
      - selinux

- name: STIG RHEL7 V-71991 Check 2
  shell: /sbin/sestatus 2>/dev/null | awk '/targeted/'
  args:
    executable: /bin/bash
  register: check2_71991
  ignore_errors: True
  changed_when: False
  tags:
      - V-71991
      - selinux

- name: STIG RHEL7 V-71991 Report
  set_fact: 
    status_71991: "{{ 'fail' if (check2_71991.stdout == '' ) else 'pass'}}"
  tags:
      - V-71991
      - selinux

