#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-01: Updated to perform actual check
#
#----------

- name: STIG RHEL7 V-72023 Check
  shell: ls -ld `cut -d":" -f1,3,6 /etc/passwd |egrep ':[0-9]{4}:'|cut -d":" -f3`
  args:
    executable: /bin/bash
  register: check1_72023
  ignore_errors: True
  changed_when: False
  tags:
      - V-72023
      - find
      - etcpasswd

- name: STIG RHEL7 V-72023 Check 2
  shell: cut -d":" -f1,3,6 /etc/passwd |egrep ':[0-9]{4}:'|cut -d":" -f1| while read USER; do find `grep ^$USER":" /etc/passwd |cut -d":" -f6` ! -user $USER -ls ;done
  args:
    executable: /bin/bash
  register: check2_72023
  ignore_errors: True
  changed_when: False
  tags:
      - V-72023
      - find
      - etcpasswd

- name: STIG RHEL7 V-72023 Report
  set_fact: 
    status_72023: "{{ 'fail' if (check2_72023.stdout != '') else 'pass'}}"
  tags:
      - V-72023
      - find
      - etcpasswd


