#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-72075 Check
  shell: |
      echo -e "\n    ls / | while read DIR; do find /$DIR \( -fstype nfs -o -fstype objfs -o -fstype proc \) -prune -o -name grub.cfg -exec ls -la {} \; ; done"; ls / | while read DIR; do find /$DIR \( -fstype nfs -o -fstype objfs -o -fstype proc \) -prune -o -name grub.cfg -exec ls -la {} \; ; done; \
      echo -e "\n    grep -c 'menuentry ' /boot/grub2/grub.cfg"; grep -c 'menuentry ' /boot/grub2/grub.cfg; \
      echo -e "\n    grep 'set root' /boot/grub2/grub.cfg"; grep 'set root' /boot/grub2/grub.cfg;
  args:
    executable: /bin/bash
  register: check1_72075
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72075 Check 2
  shell:  ls / | while read DIR; do find /$DIR \( -fstype nfs -o -fstype objfs -o -fstype proc \) -prune -o -name grub.cfg -exec ls -la {} \; ; done | awk '!/\/boot\/grub2\/grub.cfg/' 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72075
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72075 Check 3
  shell: grep 'set root' /boot/grub2/grub.cfg | awk '!/hd0/' 2>/dev/null
  args:
    executable: /bin/bash
  register: check3_72075
  ignore_errors: True
  changed_when: False

- name: STIG RHEL7 V-72075 Report
  set_fact: 
    status_72075: "{{ 'fail' if (check2_72075.stdout != '' or check3_72075.stdout != '' ) else 'pass'}}"
