#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
# Ver 2, 2019-05-09: Added inactive check JHMF
#
#----------

- name: STIG RHEL7 V-72057 Check
  shell: systemctl status kdump.service 2>&1
  args:
    executable: /bin/bash
  register: check1_72057
  ignore_errors: True
  changed_when: False
 
- name: STIG RHEL7 V-72057 Check 2
  shell: systemctl status kdump.service |grep "^   Active. inactive (dead)$" 2>/dev/null
  args:
    executable: /bin/bash
  register: check2_72057
  ignore_errors: True
  changed_when: False

- name: V-72057 Pass
  set_fact:
    #status_72057: "{{ 'fail' if (check2_72057.stdout == '' and REPORT == 1) else 'pass'}}"
    status_72057: "{{ 'fail' if (check2_72057.stdout == '' ) else 'pass'}}"

