#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-04-18: Baseline, based on DISA RHEL7 STIGS v2r2.
#
#----------

- name: STIG RHEL7 V-71913 Check
  shell: grep minclass /etc/security/pwquality.conf
  args:
    executable: /bin/bash
  register: check1_71913
  ignore_errors: True
  changed_when: False
  tags:
      - V-71913
      - pwquality

- name: STIG RHEL7 V-71913 Check 2
  shell: grep minclass /etc/security/pwquality.conf 2>/dev/null | awk '!/^#/ && $3 > /4/'
  args:
    executable: /bin/bash
  register: check2_71913
  ignore_errors: True
  changed_when: False
  tags:
      - V-71913
      - pwquality

- name: STIG RHEL7 V-71913 Report
  set_fact: 
    status_71913: "{{ 'fail' if (check2_71913.stdout == '' ) else 'pass'}}"
  tags:
      - V-71913
      - pwquality

