#--------------------
#
# Project: NAWCAD Data Center Automation
# File:    Ansible tasks for RHEL7 STIG check
# Author:  Andrew Darley, Josha Loscar, John Faber, Jordan Tyler, & Nate Vanucci
# Date:    2019-04-18
#
# Change History:
#
# Ver 1, 2019-05-13; New check. Instudes GNOME check for NA
# Ver 3, 2019-06-18: Re-wrote yum checks to output text if package not found, per. IA.  JHMF
#
#----------

- name: STIG RHEL7 V-73157 Check 1
  shell: yum list installed -q gnome* 2>&1; grep system-db /etc/dconf/profile/user 2.&1; grep -i lock-delay /etc/dconf/db/local.d/locks/* 2.&1
  args:
    executable: /bin/bash
  ignore_errors: True
  register: check1_73157
  #ignore_errors: True
  changed_when: False
  tags:
      - V-73157
      - yum
      - gnome

- name: STIG RHEL7 V-73157 Check 2
  shell: yum list installed -q gnome* 2>&1 |egrep "gnome|^Error"
  args:
    executable: /bin/bash
  register: check2_73157
  ignore_errors: True
  changed_when: False
  tags:
      - V-73157
      - yum
      - gnome

- name: STIG RHEL7 V-73157 Check 3
  shell: grep system-db /etc/dconf/profile/user 2>/dev/null
  args:
    executable: /bin/bash
  register: check3_73157
  ignore_errors: True
  changed_when: False
  tags:
      - V-73157
      - yum
      - gnome

- name: STIG RHEL7 V-73157 Check 4
  shell: grep -x "/org/gnome/desktop/session/idle-delay" /etc/dconf/db/local.d/locks/* 2>/dev/null
  args:
    executable: /bin/bash
  register: check4_73157
  ignore_errors: True
  changed_when: False
  tags:
      - V-73157
      - yum
      - gnome

- name: STIG RHEL7 V-73157 Report
  set_fact: 
    status_73157: "{{ 'NA' if (check2_73157.stdout == 'Error: No matching Packages to list') else 'fail' if ((check3_73157.stdout == '') or (check4_73157.stdout == '')) else 'pass'}}"
  tags:
      - V-73157
      - yum
      - gnome



